"""
WavesScreen — Live EEG frequency band power visualisation + band reference.
"""

import math
from collections import deque

import pyqtgraph as pg
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QPainter, QLinearGradient, QColor, QFont, QPen
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QFrame,
    QScrollArea, QPushButton,
)

from frontend.styles import Colors
from backend.engine import DataEngine


# ── Band definitions ───────────────────────────────────────────────────────────
# (eegPower dict key, display label, frequency range, hex colour)
WAVE_BANDS = [
    ("delta",     "δ  Delta",  "0 – 4 Hz",   "#6B5FCF"),
    ("theta",     "θ  Theta",  "4 – 8 Hz",   "#3D8ECC"),
    ("lowAlpha",  "α  Low",    "8 – 10 Hz",  "#25A898"),
    ("highAlpha", "α  High",   "10 – 13 Hz", "#2EB860"),
    ("lowBeta",   "β  Low",    "13 – 17 Hz", "#C8AA28"),
    ("highBeta",  "β  High",   "18 – 30 Hz", "#D06820"),
    ("lowGamma",  "γ  Low",    "30 – 40 Hz", "#C83838"),
    ("midGamma",  "γ  Mid",    "40 – 50 Hz", "#A030B0"),
]

HISTORY_LEN = 120   # seconds kept in the scrolling chart


# ── Scientific band documentation ─────────────────────────────────────────────
BAND_DOCS = {
    "delta": {
        "summary": "Deep sleep  ·  healing  ·  unconscious processing",
        "origin": (
            "Generated by thalamo-cortical circuits: the thalamus acts as a pacemaker, "
            "synchronising large populations of cortical neurons into slow, sweeping oscillations. "
            "Strongest over the frontal lobes, spreading to parietal and occipital regions during "
            "deep sleep. In the awake brain, residual delta is most visible in the prefrontal cortex."
        ),
        "mental": (
            "Dominates during Stage 3 (slow-wave) sleep — the deep, dreamless phase critical for "
            "physical restoration and immune function. Memory traces acquired during the day are "
            "replayed and consolidated into long-term storage during delta sleep. In an awake adult, "
            "elevated delta indicates profound fatigue, certain neurological conditions, or very deep "
            "meditative states. Completely normal and dominant in infant brains."
        ),
        "electrical": (
            "Highest amplitude of all EEG bands — commonly 100–200 µV during sleep, sometimes "
            "exceeding 300 µV in infants. The large amplitude reflects mass synchrony: millions of "
            "neurons depolarising and hyperpolarising in concert. On the MindWave, delta is usually "
            "the most energetic band in the raw power spectrum and will dominate if the user is "
            "drowsy or has poor electrode contact."
        ),
        "notes": (
            "During delta sleep, the brain's glymphatic system — a waste-clearance network that uses "
            "cerebrospinal fluid to flush the interstitial space — is at peak activity, removing "
            "metabolic byproducts including amyloid-beta (a protein implicated in Alzheimer's disease). "
            "Chronic delta sleep disruption is now considered a significant risk factor for "
            "neurodegenerative conditions. Even one night of delta-sleep deprivation produces measurable "
            "next-day cognitive impairment and elevated cortisol."
        ),
    },
    "theta": {
        "summary": "Drowsiness  ·  memory encoding  ·  creative insight",
        "origin": (
            "Primary generators are the hippocampus and entorhinal cortex, where theta acts as a "
            "timing clock for memory circuits. Also produced at the frontal midline (Fz electrode site) "
            "during internally directed cognition. The hippocampal theta rhythm coordinates "
            "information transfer between the hippocampus, prefrontal cortex, and amygdala, acting "
            "as a carrier signal for memory consolidation."
        ),
        "mental": (
            "The transition zone between wakefulness and sleep, and the dominant rhythm during REM "
            "(dreaming) sleep. In awake states, theta is elevated during deep meditation, creative "
            "insight, emotional processing, mind-wandering, and the early stages of memory encoding. "
            "Many people report vivid hypnagogic imagery (the dream-like hallucinations just before "
            "sleep onset) when theta power rises. Increased during novel environments and learning."
        ),
        "electrical": (
            "Medium amplitude, typically 20–100 µV in the hippocampus (not directly measurable from "
            "scalp in humans), and 10–30 µV at the frontal midline on the scalp. The MindWave "
            "captures primarily frontal-midline theta, which increases during internally directed "
            "cognition (mind-wandering, working-memory tasks, and imaginative thinking). The rhythm "
            "is less regular in humans than in rodent hippocampal recordings."
        ),
        "notes": (
            "Place cells and grid cells in the hippocampus fire in coordination with theta oscillations "
            "to encode spatial location — your brain's GPS system. Research by John O'Keefe, "
            "May-Britt Moser, and Edvard Moser (Nobel Prize in Physiology or Medicine, 2014) "
            "established this mechanism. Theta Burst Stimulation (TBS) — a form of transcranial "
            "magnetic stimulation that mimics the brain's natural theta rhythm — is now an approved "
            "treatment for treatment-resistant depression."
        ),
    },
    "lowAlpha": {
        "summary": "Resting idle  ·  eyes-closed calm  ·  unfocused",
        "origin": (
            "Thalamo-cortical feedback loops with primary generation in the occipital (visual) cortex. "
            "The thalamus gates sensory input during alpha, functioning as a traffic light that "
            "suppresses processing of irrelevant information. The occipital dominance reflects alpha's "
            "close relationship with the visual system — it was first discovered as the rhythm that "
            "appears when the eyes are closed."
        ),
        "mental": (
            "The idle rhythm of the relaxed, unfocused waking brain. Prominent when eyes are closed "
            "and attention is internally directed or diffuse. Represents a comfortable, understimulated "
            "awareness — awake but not engaged. Opening the eyes or beginning a cognitive task "
            "immediately suppresses alpha (the Berger effect or alpha blocking). Low alpha captures "
            "the slower, more relaxed end of this idle state."
        ),
        "electrical": (
            "Typically 8–50 µV over posterior (occipital-parietal) regions. Alpha is the most "
            "prominent rhythm in the resting EEG and its frequency (8–13 Hz) correlates with "
            "individual differences in cognitive processing speed — faster alpha peak frequency "
            "is associated with faster reaction times and higher IQ scores in population studies. "
            "Amplitude varies widely between individuals and is partially heritable."
        ),
        "notes": (
            "Alpha was the first brain wave ever recorded, by German psychiatrist Hans Berger in 1924. "
            "He spent five years keeping the discovery secret, fearing he would not be believed. "
            "Alpha neurofeedback training — rewarding increases in alpha power — is one of the oldest "
            "and most studied neurofeedback protocols, used in sports psychology, anxiety reduction, "
            "and creative performance enhancement since the 1960s."
        ),
    },
    "highAlpha": {
        "summary": "Alert relaxation  ·  sensory gating  ·  readiness",
        "origin": (
            "Posterior parietal cortex and sensorimotor cortex, overlapping topographically with the "
            "sensorimotor mu rhythm. High alpha reflects active inhibitory control: the cortex uses "
            "oscillatory gating to suppress task-irrelevant sensory regions, sharpening signal-to-noise "
            "ratio by quieting what does not matter rather than amplifying what does."
        ),
        "mental": (
            "Relaxed alertness and pre-performance readiness — the 'quiet mind' state that elite "
            "athletes describe before a precise physical action. Studies show alpha power over the "
            "motor cortex increases in the seconds before a golf putt, free-throw, or penalty kick, "
            "particularly in expert performers. Reflects efficient neural inhibition: the brain "
            "selectively silencing regions not needed for the upcoming action."
        ),
        "electrical": (
            "Similar amplitude to low alpha but with more focal, task-specific topography. Shows "
            "event-related synchronisation (ERS) over task-irrelevant areas and event-related "
            "desynchronisation (ERD) over task-relevant areas simultaneously — the brain performing "
            "a kind of neural spotlight, brightening what is needed and dimming everything else."
        ),
        "notes": (
            "The distinction between low and high alpha is clinically meaningful: low alpha correlates "
            "with global relaxation while high alpha reflects focused attentional control and inhibitory "
            "efficiency. Some neurofeedback protocols target specifically 10 Hz (for anxiety reduction) "
            "or 12 Hz (for attention enhancement) to exploit this dissociation. Higher individual alpha "
            "peak frequency is associated with better working memory capacity."
        ),
    },
    "lowBeta": {
        "summary": "Calm focus  ·  normal waking cognition  ·  motor readiness",
        "origin": (
            "Motor and sensorimotor cortex (the sensorimotor mu/beta rhythm at 12–15 Hz), frontal "
            "association areas, and parietal lobes. The sensorimotor beta is particularly well-studied: "
            "it reflects the motor system's 'standby' state, ready to act but not currently moving. "
            "Frontal low beta reflects active engagement with routine cognitive tasks."
        ),
        "mental": (
            "The rhythm of calm, alert wakefulness and focused but unstressed thinking. "
            "This is the productive 'deep work' state — engaged with a task, thinking clearly, "
            "not anxious or distracted. The sensorimotor component shows a characteristic suppression "
            "(event-related desynchronisation) during voluntary movement and a rebound increase "
            "afterward, thought to reflect re-establishment of inhibitory motor control."
        ),
        "electrical": (
            "Amplitude typically 5–20 µV — lower than alpha because beta reflects desynchronised, "
            "local, fast processing rather than global synchrony. The post-movement beta rebound "
            "peaks approximately 500–1000 ms after movement completion and is a reliable marker "
            "of sensorimotor circuit integrity used in motor rehabilitation and BCI (brain-computer "
            "interface) research."
        ),
        "notes": (
            "Sensorimotor rhythm (SMR, 12–15 Hz) neurofeedback was one of the earliest BCI protocols, "
            "developed by Barry Sterman at UCLA in the 1960s after he accidentally discovered that "
            "cats trained to increase SMR were resistant to seizures from a rocket-fuel compound. "
            "This led to the first successful neurofeedback treatment of epilepsy. SMR training is "
            "still used clinically for seizure disorders, ADHD, and insomnia."
        ),
    },
    "highBeta": {
        "summary": "Stress  ·  anxiety  ·  intense analytical thinking",
        "origin": (
            "Prefrontal cortex and widespread across the cortex during arousal. Generated by "
            "desynchronised, rapidly firing cortical networks under high cognitive or emotional load. "
            "Important caveat: high beta overlaps significantly with electromyographic (EMG) artifact "
            "from facial and scalp muscles. Jaw clenching, frowning, or forehead tension will "
            "dramatically inflate high-beta readings on the MindWave's frontal electrode."
        ),
        "mental": (
            "Elevated during stress, anxiety, worry, stimulant effects (caffeine, amphetamines), "
            "and intense analytical thinking. The 'overthinking' rhythm. While brief high-beta bursts "
            "can accompany productive concentrated effort, sustained elevation is associated with "
            "cortisol release, muscle tension, and cognitive fatigue. Dominant during arguments, "
            "performance anxiety, exam stress, and rumination."
        ),
        "electrical": (
            "Lower amplitude than low beta (1–10 µV at scalp), reflecting rapid, desynchronised "
            "cortical firing. The overlap with EMG artifact (muscle electrical activity) below 30 Hz "
            "makes it the noisiest band in consumer EEG. If you see unexpectedly high values here, "
            "relax your jaw, stop frowning, and ensure the headset is seated firmly — these simple "
            "steps often reduce apparent high-beta by 50% or more."
        ),
        "notes": (
            "Elevated right-frontal high-beta asymmetry (right > left prefrontal beta) is a "
            "well-replicated biomarker of trait anxiety and depression in research EEG. Conversely, "
            "elevated left-frontal beta is associated with approach motivation and positive affect — "
            "the basis for frontal alpha asymmetry research in affective neuroscience. "
            "Beta coherence between frontal regions is also studied as a marker of working-memory "
            "load and executive function."
        ),
    },
    "lowGamma": {
        "summary": "Feature binding  ·  insight  ·  cross-modal integration",
        "origin": (
            "Widespread across the neocortex, generated by networks of fast-spiking GABAergic "
            "interneurons (particularly parvalbumin-positive basket cells) that drive pyramidal "
            "cell populations into synchronised bursts. Long-range gamma synchrony between distant "
            "brain regions (e.g., prefrontal and parietal cortex) is thought to coordinate the "
            "integration and binding of information across the brain."
        ),
        "mental": (
            "Associated with high-level cognitive processing and the binding of separate features "
            "into coherent conscious percepts — for example, combining colour, shape, motion, and "
            "sound into the unified experience of 'a red ball bouncing.' Bursts of gamma activity "
            "accompany moments of insight and 'aha' experiences. Experienced meditators (thousands "
            "of hours of practice) show elevated resting gamma compared to novices."
        ),
        "electrical": (
            "Very low amplitude (1–5 µV at scalp) and easily contaminated by EMG artifact above "
            "30 Hz. Reliable measurement requires controlled conditions, high-quality gel electrodes, "
            "and independent component analysis (ICA) to separate neural from muscle signals. "
            "Consumer EEG readings in this band are approximate and should be interpreted as "
            "indicative rather than precise. Higher values likely reflect some EMG component."
        ),
        "notes": (
            "The 40 Hz gamma rhythm is at the centre of consciousness research. Francis Crick and "
            "Christof Koch proposed in 1990 that 40 Hz oscillations might be the neural correlate "
            "of visual consciousness — the mechanism by which the brain binds disparate sensory "
            "features into a single unified experience (the 'binding problem'). This hypothesis "
            "remains influential and debated. More recently, 40 Hz sensory entrainment (GENUS — "
            "Gamma Entrainment Using Sensory Stimuli) has shown dramatic reductions in amyloid-beta "
            "and tau pathology in Alzheimer's mouse models, and human trials are ongoing."
        ),
    },
    "midGamma": {
        "summary": "Consciousness boundary  ·  extreme alertness  ·  thalamo-cortical resonance",
        "origin": (
            "Similar interneuron circuits to low gamma, with additional involvement of thalamo-cortical "
            "loops cycling at ~40 times per second. The 40 Hz thalamo-cortical resonance — proposed "
            "by Francis Crick and famously studied by Rodolfo Llinás — describes a reverberant loop "
            "between the thalamus and layer VI of the cortex that may be fundamental to maintaining "
            "the waking conscious state."
        ),
        "mental": (
            "The outer boundary of conventional EEG measurement and a zone of active scientific debate. "
            "Associated with extreme alertness, peak attentional states, and the highest levels of "
            "perceptual integration. Long-term meditators with tens of thousands of hours of practice "
            "show extraordinary mid-gamma power and synchrony at rest — evidence that sustained mental "
            "training can permanently alter high-frequency oscillatory dynamics. Disrupted during "
            "anaesthesia and in disorders of consciousness."
        ),
        "electrical": (
            "Extremely low amplitude (<2 µV at scalp), heavily contaminated by EMG artifact above "
            "40 Hz. Reliable measurement is essentially impossible with a single frontal dry electrode. "
            "Research-grade 40 Hz measurements require multi-electrode arrays, conductive gel, "
            "and sophisticated signal processing. Consumer EEG readings in this band should be "
            "treated as rough estimates heavily influenced by muscle and movement artifact."
        ),
        "notes": (
            "In a landmark 2004 study, Antoine Lutz and Richard Davidson (with Tibetan monk Matthieu "
            "Ricard, described in the press as 'the happiest man alive') found that monks in "
            "compassion meditation showed gamma synchrony 25–30× stronger than novice meditators — "
            "among the highest amplitude gamma oscillations ever recorded in a healthy human brain. "
            "This study helped establish contemplative neuroscience as a field and demonstrated that "
            "the adult brain retains substantial capacity for experience-dependent plasticity. "
            "Ricard has since participated in over 100 neuroscience studies."
        ),
    },
}


# ── Band meter (custom-painted animated equaliser bar) ─────────────────────────

class _BandMeter(QWidget):

    METER_W = 56
    METER_H = 130
    LABEL_H = 38

    def __init__(self, label: str, freq: str, color: str, parent=None):
        super().__init__(parent)
        self.setFixedSize(self.METER_W, self.METER_H + self.LABEL_H + 20)
        self._label = label
        self._freq  = freq
        self._color = QColor(color)
        self._value = 0.0

    def set_value(self, v: float) -> None:
        self._value = max(0.0, min(100.0, v))
        self.update()

    def paintEvent(self, _event) -> None:
        p = QPainter(self)
        p.setRenderHint(QPainter.RenderHint.Antialiasing)

        W, BAR_X, BAR_W = self.width(), 8, self.width() - 16
        BAR_T, BAR_H, R  = 20, self.METER_H, 5

        p.setPen(Qt.PenStyle.NoPen)
        p.setBrush(QColor("#1a1a22"))
        p.drawRoundedRect(BAR_X, BAR_T, BAR_W, BAR_H, R, R)

        fill_h = max(2, int(BAR_H * self._value / 100))
        fill_y = BAR_T + BAR_H - fill_h
        col_top, col_bot = QColor(self._color), QColor(self._color)
        col_top.setAlphaF(1.0)
        col_bot.setAlphaF(0.25)
        grad = QLinearGradient(0, fill_y, 0, fill_y + fill_h)
        grad.setColorAt(0.0, col_top)
        grad.setColorAt(1.0, col_bot)
        p.setBrush(grad)
        p.drawRoundedRect(BAR_X, fill_y, BAR_W, fill_h, R, R)

        if self._value > 2:
            glow = QColor(self._color)
            glow.setAlphaF(0.9)
            p.setPen(QPen(glow, 2))
            p.drawLine(BAR_X + 3, fill_y + 1, BAR_X + BAR_W - 3, fill_y + 1)

        f_val = QFont("Inter"); f_val.setPixelSize(10); f_val.setBold(True)
        p.setFont(f_val)
        p.setPen(self._color)
        p.drawText(0, 2, W, 16,
                   Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignTop,
                   f"{self._value:.1f}%")

        label_y = BAR_T + BAR_H + 6
        f_lbl = QFont("Inter"); f_lbl.setPixelSize(10); f_lbl.setBold(True)
        p.setFont(f_lbl)
        p.setPen(QColor(Colors.TEXT_PRIMARY))
        p.drawText(0, label_y, W, 16,
                   Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignTop,
                   self._label)

        f_freq = QFont("Inter"); f_freq.setPixelSize(9)
        p.setFont(f_freq)
        p.setPen(QColor(Colors.TEXT_MUTED))
        p.drawText(0, label_y + 18, W, 14,
                   Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignTop,
                   self._freq)
        p.end()


# ── Band documentation accordion ──────────────────────────────────────────────

class _BandDocEntry(QWidget):
    """Collapsible accordion card for one EEG band."""

    _SECTION_TITLES = [
        ("origin",    "Brain origin & physiology"),
        ("mental",    "Mental & cognitive correlates"),
        ("electrical","Electrical properties"),
        ("notes",     "Research & significance"),
    ]

    def __init__(self, key: str, label: str, freq: str, color: str,
                 doc: dict, parent=None):
        super().__init__(parent)
        self._expanded = False
        self._color    = color
        self._doc      = doc

        vl = QVBoxLayout(self)
        vl.setContentsMargins(0, 0, 0, 0)
        vl.setSpacing(0)

        # ── Header ────────────────────────────────────────────────────────────
        self._hdr = QWidget()
        self._hdr.setCursor(Qt.CursorShape.PointingHandCursor)
        self._set_hdr_style(hovered=False)

        hl = QHBoxLayout(self._hdr)
        hl.setContentsMargins(16, 13, 16, 13)
        hl.setSpacing(12)

        accent_bar = QFrame()
        accent_bar.setFixedSize(3, 22)
        accent_bar.setStyleSheet(f"background: {color}; border-radius: 2px;")
        hl.addWidget(accent_bar)

        name_lbl = QLabel(label.replace("  ", " "))
        name_lbl.setFixedWidth(72)
        name_lbl.setStyleSheet(
            f"color: {color}; font-size: 13px; font-weight: 700; background: transparent;"
        )
        hl.addWidget(name_lbl)

        freq_badge = QLabel(freq)
        freq_badge.setStyleSheet(
            f"color: {Colors.TEXT_MUTED}; font-size: 10px; "
            f"background: {Colors.BG_APP}; border-radius: 4px; "
            f"padding: 2px 8px; border: 1px solid {Colors.BORDER};"
        )
        hl.addWidget(freq_badge)

        hl.addSpacing(8)

        summary_lbl = QLabel(doc.get("summary", ""))
        summary_lbl.setStyleSheet(
            f"color: {Colors.TEXT_SECONDARY}; font-size: 11px; background: transparent;"
        )
        hl.addWidget(summary_lbl, 1)

        self._arrow = QLabel("▶")
        self._arrow.setStyleSheet(
            f"color: {Colors.TEXT_MUTED}; font-size: 9px; background: transparent;"
        )
        hl.addWidget(self._arrow)

        vl.addWidget(self._hdr)

        # ── Body (hidden when collapsed) ──────────────────────────────────────
        self._body = QWidget()
        self._body.setVisible(False)
        self._body.setStyleSheet(
            f"background: {Colors.BG_APP}; "
            f"border-left: 2px solid {color}44; "
            f"border-bottom-left-radius: 8px; border-bottom-right-radius: 8px;"
        )

        bl = QVBoxLayout(self._body)
        bl.setContentsMargins(32, 18, 24, 18)
        bl.setSpacing(16)

        for field, title in self._SECTION_TITLES:
            text = doc.get(field, "")
            if not text:
                continue
            sec_row = QHBoxLayout()
            sec_row.setSpacing(10)
            sec_row.setContentsMargins(0, 0, 0, 0)

            sec_dot = QFrame()
            sec_dot.setFixedSize(6, 6)
            sec_dot.setStyleSheet(
                f"background: {color}; border-radius: 3px;"
            )
            sec_row.addWidget(sec_dot, 0, Qt.AlignmentFlag.AlignTop)
            sec_row.addSpacing(2)

            col = QVBoxLayout()
            col.setSpacing(5)
            sec_lbl = QLabel(title.upper())
            sec_lbl.setStyleSheet(
                f"color: {color}; font-size: 9px; font-weight: 700; "
                f"letter-spacing: 1px; background: transparent;"
            )
            body_lbl = QLabel(text)
            body_lbl.setWordWrap(True)
            body_lbl.setStyleSheet(
                f"color: {Colors.TEXT_SECONDARY}; font-size: 12px; "
                f"line-height: 160%; background: transparent;"
            )
            col.addWidget(sec_lbl)
            col.addWidget(body_lbl)
            sec_row.addLayout(col)
            bl.addLayout(sec_row)

        vl.addWidget(self._body)

        # ── Separator line ────────────────────────────────────────────────────
        sep = QFrame()
        sep.setFixedHeight(1)
        sep.setStyleSheet(f"background: {Colors.BORDER};")
        vl.addWidget(sep)

        # Wire mouse events
        self._hdr.mousePressEvent  = lambda e: self._toggle() if e.button() == Qt.MouseButton.LeftButton else None
        self._hdr.enterEvent       = lambda e: self._set_hdr_style(hovered=True)
        self._hdr.leaveEvent       = lambda e: self._set_hdr_style(hovered=False)

    def _set_hdr_style(self, hovered: bool) -> None:
        bg = Colors.BG_SURFACE if (hovered or self._expanded) else Colors.BG_CARD
        radius = "border-radius: 8px 8px 0 0;" if self._expanded else "border-radius: 8px;"
        self._hdr.setStyleSheet(f"background: {bg}; {radius}")

    def _toggle(self) -> None:
        self._expanded = not self._expanded
        self._body.setVisible(self._expanded)
        self._arrow.setText("▼" if self._expanded else "▶")
        self._set_hdr_style(hovered=False)


class _BandReferenceSection(QWidget):
    """Section header + accordion entries for all 8 bands."""

    def __init__(self, parent=None):
        super().__init__(parent)
        vl = QVBoxLayout(self)
        vl.setContentsMargins(0, 0, 0, 0)
        vl.setSpacing(0)

        # Section header row
        hdr_row = QHBoxLayout()
        hdr_row.setContentsMargins(0, 0, 0, 12)

        sec_lbl = QLabel("BAND REFERENCE")
        sec_lbl.setStyleSheet(
            f"color: {Colors.TEXT_MUTED}; font-size: 9px; "
            f"font-weight: 700; letter-spacing: 1.5px;"
        )
        hdr_row.addWidget(sec_lbl)
        hdr_row.addStretch()

        self._toggle_all_btn = QPushButton("Expand all")
        self._toggle_all_btn.setFixedHeight(24)
        self._toggle_all_btn.setStyleSheet(
            f"QPushButton {{ background: transparent; border: 1px solid {Colors.BORDER}; "
            f"border-radius: 5px; color: {Colors.TEXT_MUTED}; font-size: 10px; padding: 0 10px; }}"
            f"QPushButton:hover {{ border-color: {Colors.BORDER_LIGHT}; color: {Colors.TEXT_SECONDARY}; }}"
        )
        self._toggle_all_btn.clicked.connect(self._toggle_all)
        hdr_row.addWidget(self._toggle_all_btn)
        vl.addLayout(hdr_row)

        # Container with a card background
        container = QWidget()
        container.setStyleSheet(
            f"background: {Colors.BG_CARD}; border-radius: 10px;"
        )
        cl = QVBoxLayout(container)
        cl.setContentsMargins(0, 0, 0, 0)
        cl.setSpacing(0)

        self._entries: list[_BandDocEntry] = []
        for key, label, freq, color in WAVE_BANDS:
            entry = _BandDocEntry(key, label, freq, color, BAND_DOCS[key])
            self._entries.append(entry)
            cl.addWidget(entry)

        vl.addWidget(container)
        self._all_expanded = False

    def _toggle_all(self) -> None:
        self._all_expanded = not self._all_expanded
        for entry in self._entries:
            if entry._expanded != self._all_expanded:
                entry._toggle()
        self._toggle_all_btn.setText(
            "Collapse all" if self._all_expanded else "Expand all"
        )


# ── Waves screen ───────────────────────────────────────────────────────────────

class WavesScreen(QWidget):

    def __init__(self, engine: DataEngine, parent=None):
        super().__init__(parent)
        self._engine  = engine
        self._history: dict[str, deque] = {
            key: deque(maxlen=HISTORY_LEN) for key, *_ in WAVE_BANDS
        }
        self._curves: dict[str, pg.PlotDataItem] = {}
        self._meters: dict[str, _BandMeter]      = {}
        self._build_ui()
        self._engine.new_scores.connect(self._on_scores, Qt.ConnectionType.QueuedConnection)

    def _build_ui(self) -> None:
        # Outer layout holds a scroll area so the docs section is reachable
        outer = QVBoxLayout(self)
        outer.setContentsMargins(0, 0, 0, 0)
        outer.setSpacing(0)

        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        scroll.setStyleSheet("background: transparent;")
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

        inner = QWidget()
        inner.setStyleSheet("background: transparent;")
        root = QVBoxLayout(inner)
        root.setContentsMargins(32, 28, 32, 32)
        root.setSpacing(0)

        # ── Header ────────────────────────────────────────────────────────────
        title = QLabel("Brain Waves")
        title.setStyleSheet(
            "font-size: 22px; font-weight: 700; letter-spacing: -0.5px;"
        )
        root.addWidget(title)
        root.addSpacing(4)

        sub = QLabel(
            "Live EEG frequency-band power from your headset  ·  "
            "each bar shows that band's share of total activity"
        )
        sub.setStyleSheet(f"color: {Colors.TEXT_MUTED}; font-size: 11px;")
        root.addWidget(sub)
        root.addSpacing(24)

        # ── Live meters ───────────────────────────────────────────────────────
        lbl_meters = QLabel("LIVE BAND POWER")
        lbl_meters.setStyleSheet(
            f"color: {Colors.TEXT_MUTED}; font-size: 9px; font-weight: 700; letter-spacing: 1.5px;"
        )
        root.addWidget(lbl_meters)
        root.addSpacing(12)

        meters_card = QWidget()
        meters_card.setStyleSheet(
            f"background: {Colors.BG_CARD}; border-radius: 12px;"
        )
        meters_l = QHBoxLayout(meters_card)
        meters_l.setContentsMargins(20, 20, 20, 16)
        meters_l.setSpacing(12)
        for key, label, freq, color in WAVE_BANDS:
            m = _BandMeter(label, freq, color)
            self._meters[key] = m
            meters_l.addWidget(m, alignment=Qt.AlignmentFlag.AlignHCenter)
        meters_l.addStretch()
        root.addWidget(meters_card)
        root.addSpacing(24)

        # ── History chart ─────────────────────────────────────────────────────
        lbl_hist = QLabel("BAND HISTORY  (last 2 min)")
        lbl_hist.setStyleSheet(
            f"color: {Colors.TEXT_MUTED}; font-size: 9px; font-weight: 700; letter-spacing: 1.5px;"
        )
        root.addWidget(lbl_hist)
        root.addSpacing(8)

        legend_row = QHBoxLayout()
        legend_row.setSpacing(14)
        for _, label, _freq, color in WAVE_BANDS:
            dot = QLabel("●")
            dot.setStyleSheet(f"color: {color}; font-size: 8px;")
            lname = QLabel(label.replace("  ", " "))
            lname.setStyleSheet(f"color: {Colors.TEXT_SECONDARY}; font-size: 10px;")
            legend_row.addWidget(dot)
            legend_row.addWidget(lname)
        legend_row.addStretch()
        root.addLayout(legend_row)
        root.addSpacing(6)

        self._plot = pg.PlotWidget()
        self._plot.setBackground(Colors.BG_CARD)
        self._plot.setFixedHeight(220)
        self._plot.setMouseEnabled(x=False, y=False)
        self._plot.hideButtons()
        self._plot.setMenuEnabled(False)
        self._plot.setXRange(0, HISTORY_LEN - 1, padding=0)
        self._plot.setYRange(0, 100, padding=0.02)

        left_ax = self._plot.getAxis("left")
        left_ax.setLabel("% of total", color=Colors.TEXT_MUTED)
        left_ax.setTextPen(pg.mkPen(Colors.TEXT_MUTED))
        left_ax.setPen(pg.mkPen(Colors.BORDER))
        bot_ax = self._plot.getAxis("bottom")
        bot_ax.setTextPen(pg.mkPen(Colors.TEXT_MUTED))
        bot_ax.setPen(pg.mkPen(Colors.BORDER))

        self._plot.showGrid(x=False, y=True, alpha=0.12)
        for key, _label, _freq, color in WAVE_BANDS:
            curve = self._plot.plot([], [], pen=pg.mkPen(color, width=1.8), antialias=True)
            self._curves[key] = curve
        root.addWidget(self._plot)
        root.addSpacing(8)

        self._notice = QLabel(
            "Waiting for headset data  ·  put on your headset and ensure good electrode contact"
        )
        self._notice.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self._notice.setStyleSheet(
            f"color: {Colors.TEXT_MUTED}; font-size: 11px; font-style: italic;"
        )
        root.addWidget(self._notice)
        root.addSpacing(28)

        # ── Band reference documentation ──────────────────────────────────────
        root.addWidget(_BandReferenceSection())
        root.addStretch()

        scroll.setWidget(inner)
        outer.addWidget(scroll)

    def _on_scores(self, pkt) -> None:
        bands = pkt.raw_bands
        if not bands:
            return
        total  = sum(bands.values()) or 1
        normed = {key: bands.get(key, 0) / total * 100 for key, *_ in WAVE_BANDS}

        if self._notice.isVisible():
            self._notice.setVisible(False)

        for key, pct in normed.items():
            if key in self._meters:
                self._meters[key].set_value(pct)
            self._history[key].append(pct)

        n   = len(next(iter(self._history.values())))
        pad = HISTORY_LEN - n
        xs  = list(range(HISTORY_LEN))
        for key in normed:
            ys = list(self._history[key]) + [math.nan] * pad
            curve = self._curves.get(key)
            if curve is not None:
                try:
                    curve.setData(xs, ys)
                except RuntimeError:
                    pass
